import os
import sys
import django

# Ensure project root is on sys.path so top-level packages (like `config`) import correctly
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from university.models import Region, University, AdditionalResource


def seed_regions():
    regions_data = [
        {"name_uz": "Toshkent shahri",               "name_ru": "Город Ташкент",                    "name_en": "Tashkent City"},
        {"name_uz": "Toshkent viloyati",             "name_ru": "Ташкентская область",               "name_en": "Tashkent Region"},
        {"name_uz": "Samarqand viloyati",            "name_ru": "Самаркандская область",             "name_en": "Samarkand Region"},
        {"name_uz": "Buxoro viloyati",               "name_ru": "Бухарская область",                 "name_en": "Bukhara Region"},
        {"name_uz": "Farg'ona viloyati",             "name_ru": "Ферганская область",                "name_en": "Fergana Region"},
        {"name_uz": "Xorazm viloyati",               "name_ru": "Хорезмская область",                "name_en": "Khorezm Region"},
        {"name_uz": "Andijon viloyati",              "name_ru": "Андижанская область",               "name_en": "Andijan Region"},
        {"name_uz": "Namangan viloyati",             "name_ru": "Наманганская область",              "name_en": "Namangan Region"},
        {"name_uz": "Qashqadaryo viloyati",          "name_ru": "Кашкадарьинская область",           "name_en": "Kashkadarya Region"},
        {"name_uz": "Surxondaryo viloyati",          "name_ru": "Сурхандарьинская область",          "name_en": "Surkhandarya Region"},
        {"name_uz": "Jizzax viloyati",               "name_ru": "Джизакская область",                "name_en": "Jizzakh Region"},
        {"name_uz": "Sirdaryo viloyati",             "name_ru": "Сырдарьинская область",             "name_en": "Sirdarya Region"},
        {"name_uz": "Navoiy viloyati",               "name_ru": "Навоийская область",                "name_en": "Navoiy Region"},
        {"name_uz": "Qoraqalpog'iston Respublikasi", "name_ru": "Республика Каракалпакстан",         "name_en": "Republic of Karakalpakstan"},
    ]
    region_map = {}
    for r in regions_data:
        obj, created = Region.objects.update_or_create(
            name_en=r["name_en"],
            defaults={"name_uz": r["name_uz"], "name_ru": r["name_ru"]},
        )
        region_map[r["name_en"]] = obj
        print(f"  Region: {obj.name_uz} ({'yangi' if created else 'yangilandi'})")
    return region_map


def seed_universities(region_map):
    universities_data = [

        # ═══════════════════════════════════════════
        #  TOSHKENT SHAHRI  (17 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Tashkent City",
            "name_uz": "O'zbekiston Milliy Universiteti",
            "name_ru": "Национальный университет Узбекистана",
            "name_en": "National University of Uzbekistan",
            "postal_address_uz": "Toshkent shahri, Universitet ko'chasi 4",
            "postal_address_ru": "г. Ташкент, ул. Университетская 4",
            "postal_address_en": "4 University Street, Tashkent",
            "phone_number": "+998712460224",
            "email": "info@nuu.uz",
            "website": "https://nuu.uz",
            "faculties_count": 16, "directions_count": 120,
            "students_count": 30000, "professors_count": 1500,
            "latitude": 41.3468, "longitude": 69.2066,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Islom Karimov nomidagi Toshkent Davlat Texnika Universiteti",
            "name_ru": "Ташкентский государственный технический университет имени Ислама Каримова",
            "name_en": "Tashkent State Technical University named after Islam Karimov",
            "postal_address_uz": "Toshkent shahri, Universitet ko'chasi 2",
            "postal_address_ru": "г. Ташкент, ул. Университетская 2",
            "postal_address_en": "2 University Street, Tashkent",
            "phone_number": "+998712460524",
            "email": "info@tdtu.uz",
            "website": "https://tdtu.uz",
            "faculties_count": 12, "directions_count": 80,
            "students_count": 20000, "professors_count": 1000,
            "latitude": 41.3430, "longitude": 69.2080,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Tibbiyot Akademiyasi",
            "name_ru": "Ташкентская медицинская академия",
            "name_en": "Tashkent Medical Academy",
            "postal_address_uz": "Toshkent shahri, Farabi ko'chasi 2",
            "postal_address_ru": "г. Ташкент, ул. Фараби 2",
            "postal_address_en": "2 Farabi Street, Tashkent",
            "phone_number": "+998712414591",
            "email": "info@tma.uz",
            "website": "https://tma.uz",
            "faculties_count": 7, "directions_count": 30,
            "students_count": 12000, "professors_count": 800,
            "latitude": 41.3375, "longitude": 69.2940,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "O'zbekiston Davlat Jahon Tillari Universiteti",
            "name_ru": "Узбекский государственный университет мировых языков",
            "name_en": "Uzbekistan State World Languages University",
            "postal_address_uz": "Toshkent shahri, Kichik halqa yo'li 21A",
            "postal_address_ru": "г. Ташкент, Малая кольцевая дорога 21А",
            "postal_address_en": "21A Small Ring Road, Tashkent",
            "phone_number": "+998712445013",
            "email": "info@uzswlu.uz",
            "website": "https://uzswlu.uz",
            "faculties_count": 8, "directions_count": 40,
            "students_count": 10000, "professors_count": 600,
            "latitude": 41.3200, "longitude": 69.2400,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Davlat Iqtisodiyot Universiteti",
            "name_ru": "Ташкентский государственный экономический университет",
            "name_en": "Tashkent State University of Economics",
            "postal_address_uz": "Toshkent shahri, Islam Karimov ko'chasi 49",
            "postal_address_ru": "г. Ташкент, ул. Ислама Каримова 49",
            "postal_address_en": "49 Islam Karimov Street, Tashkent",
            "phone_number": "+998712345678",
            "email": "info@tsue.uz",
            "website": "https://tsue.uz",
            "faculties_count": 9, "directions_count": 50,
            "students_count": 18000, "professors_count": 900,
            "latitude": 41.2995, "longitude": 69.2401,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Davlat Yuridik Universiteti",
            "name_ru": "Ташкентский государственный юридический университет",
            "name_en": "Tashkent State University of Law",
            "postal_address_uz": "Toshkent shahri, Said Baraka ko'chasi 35",
            "postal_address_ru": "г. Ташкент, ул. Саида Барака 35",
            "postal_address_en": "35 Said Baraka Street, Tashkent",
            "phone_number": "+998712444488",
            "email": "info@tsul.uz",
            "website": "https://tsul.uz",
            "faculties_count": 5, "directions_count": 18,
            "students_count": 7000, "professors_count": 400,
            "latitude": 41.3110, "longitude": 69.2820,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Muhammad al-Xorazmiy nomidagi Toshkent Axborot Texnologiyalari Universiteti",
            "name_ru": "Ташкентский университет информационных технологий имени Мухаммада ал-Хоразмий",
            "name_en": "Tashkent University of Information Technologies named after Muhammad al-Khawarizmi",
            "postal_address_uz": "Toshkent shahri, Amir Temur ko'chasi 108",
            "postal_address_ru": "г. Ташкент, пр. Амира Темура 108",
            "postal_address_en": "108 Amir Temur Avenue, Tashkent",
            "phone_number": "+998712388080",
            "email": "rector@tuit.uz",
            "website": "https://tuit.uz",
            "faculties_count": 8, "directions_count": 46,
            "students_count": 16000, "professors_count": 800,
            "latitude": 41.3495, "longitude": 69.3015,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Kimyo-Texnologiya Instituti",
            "name_ru": "Ташкентский химико-технологический институт",
            "name_en": "Tashkent Institute of Chemical Technology",
            "postal_address_uz": "Toshkent shahri, Navoiy ko'chasi 32",
            "postal_address_ru": "г. Ташкент, ул. Навои 32",
            "postal_address_en": "32 Navoiy Street, Tashkent",
            "phone_number": "+998712561401",
            "email": "info@tict.uz",
            "website": "https://tict.uz",
            "faculties_count": 6, "directions_count": 30,
            "students_count": 6000, "professors_count": 400,
            "latitude": 41.3300, "longitude": 69.2600,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "O'zbekiston Davlat San'at va Madaniyat Instituti",
            "name_ru": "Узбекский государственный институт искусств и культуры",
            "name_en": "Uzbekistan State Institute of Arts and Culture",
            "postal_address_uz": "Toshkent shahri, Amir Temur ko'chasi 31",
            "postal_address_ru": "г. Ташкент, пр. Амира Темура 31",
            "postal_address_en": "31 Amir Temur Avenue, Tashkent",
            "phone_number": "+998712567890",
            "email": "info@dsmi.uz",
            "website": "https://dsmi.uz",
            "faculties_count": 6, "directions_count": 25,
            "students_count": 4000, "professors_count": 300,
            "latitude": 41.3050, "longitude": 69.2710,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "O'zbekiston Davlat Konservatoriyasi",
            "name_ru": "Государственная консерватория Узбекистана",
            "name_en": "State Conservatory of Uzbekistan",
            "postal_address_uz": "Toshkent shahri, Pushkin ko'chasi 31",
            "postal_address_ru": "г. Ташкент, ул. Пушкина 31",
            "postal_address_en": "31 Pushkin Street, Tashkent",
            "phone_number": "+998712413812",
            "email": "info@conservatory.uz",
            "website": "https://conservatory.uz",
            "faculties_count": 5, "directions_count": 15,
            "students_count": 1500, "professors_count": 200,
            "latitude": 41.2985, "longitude": 69.2710,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "O'zbekiston Davlat Jismoniy Tarbiya va Sport Universiteti",
            "name_ru": "Узбекский государственный университет физической культуры и спорта",
            "name_en": "Uzbekistan State University of Physical Culture and Sports",
            "postal_address_uz": "Toshkent shahri, Chimkent yo'li 1",
            "postal_address_ru": "г. Ташкент, Чимкентская дорога 1",
            "postal_address_en": "1 Chimkent Road, Tashkent",
            "phone_number": "+998712565050",
            "email": "info@gtifk.uz",
            "website": "https://gtifk.uz",
            "faculties_count": 5, "directions_count": 20,
            "students_count": 5000, "professors_count": 350,
            "latitude": 41.3600, "longitude": 69.3500,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Davlat Sharqshunoslik Universiteti",
            "name_ru": "Ташкентский государственный университет востоковедения",
            "name_en": "Tashkent State University of Oriental Studies",
            "postal_address_uz": "Toshkent shahri, Shaxrisabz ko'chasi 25",
            "postal_address_ru": "г. Ташкент, ул. Шахрисабз 25",
            "postal_address_en": "25 Shahrisabz Street, Tashkent",
            "phone_number": "+998712336481",
            "email": "info@tsuos.uz",
            "website": "https://tsuos.uz",
            "faculties_count": 6, "directions_count": 22,
            "students_count": 5000, "professors_count": 320,
            "latitude": 41.2970, "longitude": 69.2740,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Toshkent Davlat Agrar Universiteti",
            "name_ru": "Ташкентский государственный аграрный университет",
            "name_en": "Tashkent State Agrarian University",
            "postal_address_uz": "Toshkent viloyati, Qibray tumani, Universitetlar ko'chasi 2",
            "postal_address_ru": "Ташкентская обл., Кибрайский р-н, ул. Университетская 2",
            "postal_address_en": "2 Universitetlar Street, Kibray, Tashkent Region",
            "phone_number": "+998712645124",
            "email": "info@tdau.uz",
            "website": "https://tdau.uz",
            "faculties_count": 8, "directions_count": 40,
            "students_count": 11000, "professors_count": 600,
            "latitude": 41.3870, "longitude": 69.3660,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Westminster Xalqaro Universiteti Toshkentda",
            "name_ru": "Международный Вестминстерский университет в Ташкенте",
            "name_en": "Westminster International University in Tashkent",
            "postal_address_uz": "Toshkent shahri, Istiqbol ko'chasi 12A",
            "postal_address_ru": "г. Ташкент, ул. Истикбол 12А",
            "postal_address_en": "12A Istiqbol Street, Tashkent",
            "phone_number": "+998712387700",
            "email": "info@wiut.uz",
            "website": "https://wiut.uz",
            "faculties_count": 4, "directions_count": 12,
            "students_count": 3500, "professors_count": 250,
            "latitude": 41.2960, "longitude": 69.2790,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Turin Politexnika Universiteti Toshkentda",
            "name_ru": "Туринский политехнический университет в Ташкенте",
            "name_en": "Turin Polytechnic University in Tashkent",
            "postal_address_uz": "Toshkent shahri, Niyozbek yo'li 17",
            "postal_address_ru": "г. Ташкент, ул. Ниёзбека 17",
            "postal_address_en": "17 Niyozbek Road, Tashkent",
            "phone_number": "+998712469100",
            "email": "info@polito.uz",
            "website": "https://polito.uz",
            "faculties_count": 3, "directions_count": 10,
            "students_count": 2000, "professors_count": 180,
            "latitude": 41.2760, "longitude": 69.2610,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "Inha Universiteti Toshkentda",
            "name_ru": "Университет Инха в Ташкенте",
            "name_en": "Inha University in Tashkent",
            "postal_address_uz": "Toshkent shahri, Ziyolilar ko'chasi 9",
            "postal_address_ru": "г. Ташкент, ул. Зиёлилар 9",
            "postal_address_en": "9 Ziyolilar Street, Tashkent",
            "phone_number": "+998712464400",
            "email": "info@inha.uz",
            "website": "https://inha.uz",
            "faculties_count": 4, "directions_count": 15,
            "students_count": 2500, "professors_count": 200,
            "latitude": 41.3660, "longitude": 69.2900,
        },
        {
            "region_en": "Tashkent City",
            "name_uz": "AKFA Universiteti",
            "name_ru": "Университет АКФА",
            "name_en": "AKFA University",
            "postal_address_uz": "Toshkent shahri, Bunyodkor ko'chasi 4",
            "postal_address_ru": "г. Ташкент, пр. Буньёдкор 4",
            "postal_address_en": "4 Bunyodkor Avenue, Tashkent",
            "phone_number": "+998712020820",
            "email": "info@akfauniversity.uz",
            "website": "https://akfauniversity.uz",
            "faculties_count": 4, "directions_count": 14,
            "students_count": 2000, "professors_count": 160,
            "latitude": 41.3530, "longitude": 69.2870,
        },

        # ═══════════════════════════════════════════
        #  TOSHKENT VILOYATI  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Tashkent Region",
            "name_uz": "Toshkent viloyati Chirchiq Davlat Pedagogika Universiteti",
            "name_ru": "Чирчикский государственный педагогический университет Ташкентской области",
            "name_en": "Chirchiq State Pedagogical University of Tashkent Region",
            "postal_address_uz": "Chirchiq shahri, Amir Temur ko'chasi 104",
            "postal_address_ru": "г. Чирчик, ул. Амира Темура 104",
            "postal_address_en": "104 Amir Temur Street, Chirchiq",
            "phone_number": "+998702600101",
            "email": "info@cspu.uz",
            "website": "https://cspu.uz",
            "faculties_count": 6, "directions_count": 28,
            "students_count": 6500, "professors_count": 380,
            "latitude": 41.4880, "longitude": 69.5810,
        },
        {
            "region_en": "Tashkent Region",
            "name_uz": "Almaliq ko'chmas mulk instituti (TDTU Olmaliq filiali)",
            "name_ru": "Алмалыкский филиал ТГТУ",
            "name_en": "Almalyk Branch of Tashkent State Technical University",
            "postal_address_uz": "Olmaliq shahri, Yoshlar ko'chasi 1",
            "postal_address_ru": "г. Алмалык, ул. Ёшлар 1",
            "postal_address_en": "1 Yoshlar Street, Almalyk",
            "phone_number": "+998702234567",
            "email": "info@almalyk-tstu.uz",
            "website": "https://tdtu.uz/branches",
            "faculties_count": 4, "directions_count": 18,
            "students_count": 4000, "professors_count": 200,
            "latitude": 40.8554, "longitude": 69.5959,
        },

        # ═══════════════════════════════════════════
        #  SAMARQAND  (4 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Samarkand Region",
            "name_uz": "Samarqand Davlat Universiteti",
            "name_ru": "Самаркандский государственный университет",
            "name_en": "Samarkand State University",
            "postal_address_uz": "Samarqand shahri, Universitet xiyoboni 15",
            "postal_address_ru": "г. Самарканд, Университетский бульвар 15",
            "postal_address_en": "15 University Boulevard, Samarkand",
            "phone_number": "+998662391140",
            "email": "devonxona@samdu.uz",
            "website": "https://samdu.uz",
            "faculties_count": 14, "directions_count": 90,
            "students_count": 25000, "professors_count": 1200,
            "latitude": 39.6465, "longitude": 66.9602,
        },
        {
            "region_en": "Samarkand Region",
            "name_uz": "Samarqand Davlat Tibbiyot Universiteti",
            "name_ru": "Самаркандский государственный медицинский университет",
            "name_en": "Samarkand State Medical University",
            "postal_address_uz": "Samarqand shahri, Amir Temur ko'chasi 18",
            "postal_address_ru": "г. Самарканд, ул. Амира Темура 18",
            "postal_address_en": "18 Amir Temur Street, Samarkand",
            "phone_number": "+998662351203",
            "email": "info@sammu.uz",
            "website": "https://sammu.uz",
            "faculties_count": 6, "directions_count": 20,
            "students_count": 8000, "professors_count": 600,
            "latitude": 39.6540, "longitude": 66.9760,
        },
        {
            "region_en": "Samarkand Region",
            "name_uz": "Samarqand Davlat Arxitektura-Qurilish Universiteti",
            "name_ru": "Самаркандский государственный архитектурно-строительный университет",
            "name_en": "Samarkand State Architectural and Civil Engineering University",
            "postal_address_uz": "Samarqand shahri, Lolazor ko'chasi 70",
            "postal_address_ru": "г. Самарканд, ул. Лолазор 70",
            "postal_address_en": "70 Lolazor Street, Samarkand",
            "phone_number": "+998662354444",
            "email": "info@samdchti.uz",
            "website": "https://samdchti.uz",
            "faculties_count": 5, "directions_count": 22,
            "students_count": 6000, "professors_count": 350,
            "latitude": 39.6700, "longitude": 66.9800,
        },
        {
            "region_en": "Samarkand Region",
            "name_uz": "Samarqand Davlat Veterinariya Tibbiyoti, Chorvachilik va Biotexnologiyalar Universiteti",
            "name_ru": "Самаркандский государственный университет ветеринарной медицины, животноводства и биотехнологий",
            "name_en": "Samarkand State University of Veterinary Medicine, Animal Husbandry and Biotechnologies",
            "postal_address_uz": "Samarqand shahri, M.Ulug'bek ko'chasi 77",
            "postal_address_ru": "г. Самарканд, ул. М.Улугбека 77",
            "postal_address_en": "77 M.Ulugbek Street, Samarkand",
            "phone_number": "+998662351110",
            "email": "info@samvet.uz",
            "website": "https://samvet.uz",
            "faculties_count": 5, "directions_count": 18,
            "students_count": 5000, "professors_count": 320,
            "latitude": 39.6580, "longitude": 66.9700,
        },

        # ═══════════════════════════════════════════
        #  BUXORO  (3 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Bukhara Region",
            "name_uz": "Buxoro Davlat Universiteti",
            "name_ru": "Бухарский государственный университет",
            "name_en": "Bukhara State University",
            "postal_address_uz": "Buxoro shahri, M.Iqbol ko'chasi 11",
            "postal_address_ru": "г. Бухара, ул. М.Икбола 11",
            "postal_address_en": "11 M.Iqbol Street, Bukhara",
            "phone_number": "+998652212914",
            "email": "info@buxdu.uz",
            "website": "https://buxdu.uz",
            "faculties_count": 12, "directions_count": 70,
            "students_count": 16000, "professors_count": 800,
            "latitude": 39.7747, "longitude": 64.4286,
        },
        {
            "region_en": "Bukhara Region",
            "name_uz": "Buxoro Muhandislik-Texnologiya Instituti",
            "name_ru": "Бухарский инженерно-технологический институт",
            "name_en": "Bukhara Engineering Technology Institute",
            "postal_address_uz": "Buxoro shahri, K.Murtazaev ko'chasi 15",
            "postal_address_ru": "г. Бухара, ул. К.Муртазаева 15",
            "postal_address_en": "15 K.Murtazaev Street, Bukhara",
            "phone_number": "+998652230011",
            "email": "info@bti.uz",
            "website": "https://bti.uz",
            "faculties_count": 6, "directions_count": 28,
            "students_count": 7000, "professors_count": 400,
            "latitude": 39.7800, "longitude": 64.4200,
        },
        {
            "region_en": "Bukhara Region",
            "name_uz": "Buxoro Davlat Tibbiyot Instituti",
            "name_ru": "Бухарский государственный медицинский институт",
            "name_en": "Bukhara State Medical Institute",
            "postal_address_uz": "Buxoro shahri, Navoiy ko'chasi 1",
            "postal_address_ru": "г. Бухара, ул. Навои 1",
            "postal_address_en": "1 Navoiy Street, Bukhara",
            "phone_number": "+998652224455",
            "email": "info@bdmi.uz",
            "website": "https://bdmi.uz",
            "faculties_count": 4, "directions_count": 12,
            "students_count": 4500, "professors_count": 300,
            "latitude": 39.7760, "longitude": 64.4150,
        },

        # ═══════════════════════════════════════════
        #  FARG'ONA  (3 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Fergana Region",
            "name_uz": "Farg'ona Davlat Universiteti",
            "name_ru": "Ферганский государственный университет",
            "name_en": "Fergana State University",
            "postal_address_uz": "Farg'ona shahri, Murabbiylar ko'chasi 19",
            "postal_address_ru": "г. Фергана, ул. Мураббийлар 19",
            "postal_address_en": "19 Murabbiylar Street, Fergana",
            "phone_number": "+998732444402",
            "email": "fdu@fdu.uz",
            "website": "https://fdu.uz",
            "faculties_count": 10, "directions_count": 60,
            "students_count": 14000, "professors_count": 700,
            "latitude": 40.3864, "longitude": 71.7828,
        },
        {
            "region_en": "Fergana Region",
            "name_uz": "Farg'ona Politexnika Instituti",
            "name_ru": "Ферганский политехнический институт",
            "name_en": "Fergana Polytechnic Institute",
            "postal_address_uz": "Farg'ona shahri, Fergana ko'chasi 86",
            "postal_address_ru": "г. Фергана, ул. Ферганская 86",
            "postal_address_en": "86 Fergana Street, Fergana",
            "phone_number": "+998732232424",
            "email": "info@ferpi.uz",
            "website": "https://ferpi.uz",
            "faculties_count": 7, "directions_count": 35,
            "students_count": 9000, "professors_count": 500,
            "latitude": 40.3800, "longitude": 71.7700,
        },
        {
            "region_en": "Fergana Region",
            "name_uz": "Farg'ona Davlat Tibbiyot Instituti",
            "name_ru": "Ферганский государственный медицинский институт",
            "name_en": "Fergana State Medical Institute",
            "postal_address_uz": "Farg'ona shahri, Olmazor ko'chasi 1",
            "postal_address_ru": "г. Фергана, ул. Олмазор 1",
            "postal_address_en": "1 Olmazor Street, Fergana",
            "phone_number": "+998732233465",
            "email": "info@fdmi.uz",
            "website": "https://fdmi.uz",
            "faculties_count": 4, "directions_count": 12,
            "students_count": 4000, "professors_count": 280,
            "latitude": 40.3910, "longitude": 71.7850,
        },

        # ═══════════════════════════════════════════
        #  ANDIJON  (3 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Andijan Region",
            "name_uz": "Andijon Davlat Universiteti",
            "name_ru": "Андижанский государственный университет",
            "name_en": "Andijan State University",
            "postal_address_uz": "Andijon shahri, Universitet ko'chasi 129",
            "postal_address_ru": "г. Андижан, ул. Университетская 129",
            "postal_address_en": "129 University Street, Andijan",
            "phone_number": "+998742233350",
            "email": "info@andpu.uz",
            "website": "https://andpu.uz",
            "faculties_count": 11, "directions_count": 65,
            "students_count": 15000, "professors_count": 750,
            "latitude": 40.7829, "longitude": 72.3440,
        },
        {
            "region_en": "Andijan Region",
            "name_uz": "Andijon Davlat Tibbiyot Instituti",
            "name_ru": "Андижанский государственный медицинский институт",
            "name_en": "Andijan State Medical Institute",
            "postal_address_uz": "Andijon shahri, Yuqori Arik ko'chasi 1",
            "postal_address_ru": "г. Андижан, ул. Юкори Арык 1",
            "postal_address_en": "1 Yuqori Arik Street, Andijan",
            "phone_number": "+998742254067",
            "email": "info@agmi.uz",
            "website": "https://agmi.uz",
            "faculties_count": 5, "directions_count": 15,
            "students_count": 6000, "professors_count": 400,
            "latitude": 40.7920, "longitude": 72.3600,
        },
        {
            "region_en": "Andijan Region",
            "name_uz": "Andijon Mashinasozlik Instituti",
            "name_ru": "Андижанский машиностроительный институт",
            "name_en": "Andijan Machine Building Institute",
            "postal_address_uz": "Andijon shahri, Bobur ko'chasi 56",
            "postal_address_ru": "г. Андижан, ул. Бабура 56",
            "postal_address_en": "56 Bobur Street, Andijan",
            "phone_number": "+998742245566",
            "email": "info@anmi.uz",
            "website": "https://anmi.uz",
            "faculties_count": 5, "directions_count": 20,
            "students_count": 5000, "professors_count": 300,
            "latitude": 40.7760, "longitude": 72.3380,
        },

        # ═══════════════════════════════════════════
        #  NAMANGAN  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Namangan Region",
            "name_uz": "Namangan Davlat Universiteti",
            "name_ru": "Наманганский государственный университет",
            "name_en": "Namangan State University",
            "postal_address_uz": "Namangan shahri, Uychi ko'chasi 316",
            "postal_address_ru": "г. Наманган, ул. Уйчи 316",
            "postal_address_en": "316 Uychi Street, Namangan",
            "phone_number": "+998692234444",
            "email": "info@namdu.uz",
            "website": "https://namdu.uz",
            "faculties_count": 9, "directions_count": 55,
            "students_count": 12000, "professors_count": 650,
            "latitude": 41.0010, "longitude": 71.6714,
        },
        {
            "region_en": "Namangan Region",
            "name_uz": "Namangan Muhandislik-Texnologiya Instituti",
            "name_ru": "Наманганский инженерно-технологический институт",
            "name_en": "Namangan Institute of Engineering and Technology",
            "postal_address_uz": "Namangan shahri, Kasansay ko'chasi 7",
            "postal_address_ru": "г. Наманган, ул. Касансай 7",
            "postal_address_en": "7 Kasansay Street, Namangan",
            "phone_number": "+998692222301",
            "email": "info@namti.uz",
            "website": "https://namti.uz",
            "faculties_count": 5, "directions_count": 25,
            "students_count": 5000, "professors_count": 300,
            "latitude": 41.0100, "longitude": 71.6600,
        },

        # ═══════════════════════════════════════════
        #  XORAZM  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Khorezm Region",
            "name_uz": "Urganch Davlat Universiteti",
            "name_ru": "Ургенчский государственный университет",
            "name_en": "Urgench State University",
            "postal_address_uz": "Urganch shahri, Hamid Olimjon ko'chasi 14",
            "postal_address_ru": "г. Ургенч, ул. Хамида Алимджана 14",
            "postal_address_en": "14 Hamid Olimjon Street, Urgench",
            "phone_number": "+998622246700",
            "email": "info@urdu.uz",
            "website": "https://urdu.uz",
            "faculties_count": 10, "directions_count": 55,
            "students_count": 13000, "professors_count": 650,
            "latitude": 41.5501, "longitude": 60.6300,
        },
        {
            "region_en": "Khorezm Region",
            "name_uz": "Xorazm Mamun Akademiyasi",
            "name_ru": "Хорезмская академия Мамуна",
            "name_en": "Khorezm Mamun Academy",
            "postal_address_uz": "Xiva shahri, Pahlavon Mahmud ko'chasi 28",
            "postal_address_ru": "г. Хива, ул. Пахлавана Махмуда 28",
            "postal_address_en": "28 Pahlavon Mahmud Street, Khiva",
            "phone_number": "+998622375001",
            "email": "info@mamun.uz",
            "website": "https://mamun.uz",
            "faculties_count": 4, "directions_count": 14,
            "students_count": 2000, "professors_count": 150,
            "latitude": 41.3784, "longitude": 60.3617,
        },

        # ═══════════════════════════════════════════
        #  QASHQADARYO  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Kashkadarya Region",
            "name_uz": "Qarshi Davlat Universiteti",
            "name_ru": "Каршинский государственный университет",
            "name_en": "Karshi State University",
            "postal_address_uz": "Qarshi shahri, Katta yo'l ko'chasi 17",
            "postal_address_ru": "г. Карши, ул. Катта йул 17",
            "postal_address_en": "17 Katta Yol Street, Karshi",
            "phone_number": "+998752242130",
            "email": "info@kardu.uz",
            "website": "https://kardu.uz",
            "faculties_count": 9, "directions_count": 50,
            "students_count": 11000, "professors_count": 600,
            "latitude": 38.8600, "longitude": 65.7900,
        },
        {
            "region_en": "Kashkadarya Region",
            "name_uz": "Qarshi Muhandislik-Iqtisodiyot Instituti",
            "name_ru": "Каршинский инженерно-экономический институт",
            "name_en": "Karshi Engineering Economics Institute",
            "postal_address_uz": "Qarshi shahri, Mustakillik ko'chasi 225",
            "postal_address_ru": "г. Карши, ул. Мустакиллик 225",
            "postal_address_en": "225 Mustakillik Street, Karshi",
            "phone_number": "+998752224455",
            "email": "info@qmii.uz",
            "website": "https://qmii.uz",
            "faculties_count": 5, "directions_count": 20,
            "students_count": 5000, "professors_count": 280,
            "latitude": 38.8660, "longitude": 65.7820,
        },

        # ═══════════════════════════════════════════
        #  SURXONDARYO  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Surkhandarya Region",
            "name_uz": "Termiz Davlat Universiteti",
            "name_ru": "Термезский государственный университет",
            "name_en": "Termez State University",
            "postal_address_uz": "Termiz shahri, F.Xo'jayev ko'chasi 43",
            "postal_address_ru": "г. Термез, ул. Ф.Ходжаева 43",
            "postal_address_en": "43 F.Khojayev Street, Termez",
            "phone_number": "+998762238813",
            "email": "info@termdu.uz",
            "website": "https://termdu.uz",
            "faculties_count": 9, "directions_count": 48,
            "students_count": 10000, "professors_count": 550,
            "latitude": 37.2240, "longitude": 67.2780,
        },
        {
            "region_en": "Surkhandarya Region",
            "name_uz": "Termiz Davlat Tibbiyot Instituti",
            "name_ru": "Термезский государственный медицинский институт",
            "name_en": "Termez State Medical Institute",
            "postal_address_uz": "Termiz shahri, Alpomish ko'chasi 3",
            "postal_address_ru": "г. Термез, ул. Алпомиш 3",
            "postal_address_en": "3 Alpomish Street, Termez",
            "phone_number": "+998762241234",
            "email": "info@tdmi.uz",
            "website": "https://tdmi.uz",
            "faculties_count": 4, "directions_count": 12,
            "students_count": 3500, "professors_count": 240,
            "latitude": 37.2300, "longitude": 67.2900,
        },

        # ═══════════════════════════════════════════
        #  JIZZAX  (1 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Jizzakh Region",
            "name_uz": "Jizzax Davlat Pedagogika Universiteti",
            "name_ru": "Джизакский государственный педагогический университет",
            "name_en": "Jizzakh State Pedagogical University",
            "postal_address_uz": "Jizzax shahri, Sharof Rashidov ko'chasi 4",
            "postal_address_ru": "г. Джизак, ул. Шарофа Рашидова 4",
            "postal_address_en": "4 Sharof Rashidov Street, Jizzakh",
            "phone_number": "+998722242290",
            "email": "info@jdpu.uz",
            "website": "https://jdpu.uz",
            "faculties_count": 8, "directions_count": 40,
            "students_count": 9000, "professors_count": 500,
            "latitude": 40.1216, "longitude": 67.8422,
        },

        # ═══════════════════════════════════════════
        #  NAVOIY  (2 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Navoiy Region",
            "name_uz": "Navoiy Davlat Konchilik va Texnologiyalar Universiteti",
            "name_ru": "Навоийский государственный горный и технологический университет",
            "name_en": "Navoi State Mining and Technologies University",
            "postal_address_uz": "Navoiy shahri, Janubiy ko'chasi 27",
            "postal_address_ru": "г. Навои, ул. Южная 27",
            "postal_address_en": "27 Janubiy Street, Navoi",
            "phone_number": "+998792232370",
            "email": "info@ngmtu.uz",
            "website": "https://ngmtu.uz",
            "faculties_count": 6, "directions_count": 30,
            "students_count": 7000, "professors_count": 420,
            "latitude": 40.0843, "longitude": 65.3791,
        },
        {
            "region_en": "Navoiy Region",
            "name_uz": "Navoiy Davlat Pedagogika Instituti",
            "name_ru": "Навоийский государственный педагогический институт",
            "name_en": "Navoi State Pedagogical Institute",
            "postal_address_uz": "Navoiy shahri, G'azalkent ko'chasi 1",
            "postal_address_ru": "г. Навои, ул. Газалкент 1",
            "postal_address_en": "1 G'azalkent Street, Navoi",
            "phone_number": "+998792241122",
            "email": "info@ndpi.uz",
            "website": "https://ndpi.uz",
            "faculties_count": 5, "directions_count": 22,
            "students_count": 4500, "professors_count": 260,
            "latitude": 40.0900, "longitude": 65.3700,
        },

        # ═══════════════════════════════════════════
        #  SIRDARYO  (1 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Sirdarya Region",
            "name_uz": "Guliston Davlat Universiteti",
            "name_ru": "Гулистанский государственный университет",
            "name_en": "Gulistan State University",
            "postal_address_uz": "Guliston shahri, Ipak yo'li ko'chasi 4",
            "postal_address_ru": "г. Гулистан, ул. Ипак йули 4",
            "postal_address_en": "4 Ipak Yoli Street, Gulistan",
            "phone_number": "+998672222014",
            "email": "info@guldu.uz",
            "website": "https://guldu.uz",
            "faculties_count": 7, "directions_count": 38,
            "students_count": 8000, "professors_count": 430,
            "latitude": 40.4895, "longitude": 68.7741,
        },

        # ═══════════════════════════════════════════
        #  QORAQALPOG'ISTON  (3 ta)
        # ═══════════════════════════════════════════
        {
            "region_en": "Republic of Karakalpakstan",
            "name_uz": "Berdax nomidagi Qoraqalpog'iston Davlat Universiteti",
            "name_ru": "Каракалпакский государственный университет имени Бердаха",
            "name_en": "Berdakh Karakalpak State University",
            "postal_address_uz": "Nukus shahri, Universitetlar ko'chasi 1",
            "postal_address_ru": "г. Нукус, ул. Университетская 1",
            "postal_address_en": "1 Universitetlar Street, Nukus",
            "phone_number": "+998612224240",
            "email": "info@karsu.uz",
            "website": "https://karsu.uz",
            "faculties_count": 11, "directions_count": 58,
            "students_count": 13000, "professors_count": 680,
            "latitude": 42.4600, "longitude": 59.6100,
        },
        {
            "region_en": "Republic of Karakalpakstan",
            "name_uz": "Ajiniyoz nomidagi Nukus Davlat Pedagogika Instituti",
            "name_ru": "Нукусский государственный педагогический институт имени Ажиниёза",
            "name_en": "Nukus State Pedagogical Institute named after Ajiniyoz",
            "postal_address_uz": "Nukus shahri, Dosnazarov ko'chasi 104",
            "postal_address_ru": "г. Нукус, ул. Досназарова 104",
            "postal_address_en": "104 Dosnazarov Street, Nukus",
            "phone_number": "+998612274550",
            "email": "info@ndpi-nukus.uz",
            "website": "https://ndpi.uz",
            "faculties_count": 6, "directions_count": 25,
            "students_count": 5000, "professors_count": 300,
            "latitude": 42.4750, "longitude": 59.6200,
        },
        {
            "region_en": "Republic of Karakalpakstan",
            "name_uz": "Nukus Davlat Tibbiyot Instituti",
            "name_ru": "Нукусский государственный медицинский институт",
            "name_en": "Nukus State Medical Institute",
            "postal_address_uz": "Nukus shahri, Qoraqalpog'iston ko'chasi 1",
            "postal_address_ru": "г. Нукус, ул. Каракалпакстан 1",
            "postal_address_en": "1 Karakalpakstan Street, Nukus",
            "phone_number": "+998612261100",
            "email": "info@ndmi.uz",
            "website": "https://ndmi.uz",
            "faculties_count": 4, "directions_count": 10,
            "students_count": 3000, "professors_count": 220,
            "latitude": 42.4680, "longitude": 59.6150,
        },
    ]

    for u in universities_data:
        region_key = u.pop("region_en")
        u["region"] = region_map.get(region_key)
        obj, created = University.objects.update_or_create(
            name_en=u["name_en"],
            defaults=u,
        )
        action = "yangi qo'shildi" if created else "yangilandi"
        print(f"  Universitet: {obj.name_uz} ({action})")

    total = University.objects.count()
    print(f"\n  Jami universitetlar soni: {total}")


def seed_resources():
    resources_data = [
        {
            "title_uz": "Oliy ta'lim, fan va innovatsiyalar vazirligi",
            "title_ru": "Министерство высшего образования, науки и инноваций",
            "title_en": "Ministry of Higher Education, Science and Innovations",
            "description_uz": "O'zbekiston Respublikasi oliy ta'lim muassasalari haqida rasmiy ma'lumotlar portali",
            "description_ru": "Официальный портал сведений о высших учебных заведениях Республики Узбекистан",
            "description_en": "Official portal with information about higher educational institutions of Uzbekistan",
            "url": "https://edu.uz",
            "icon_class": "fas fa-university",
        },
        {
            "title_uz": "Bilim va malakalarni baholash agentligi (UzBMB)",
            "title_ru": "Агентство по оценке знаний и квалификаций (UzBMB)",
            "title_en": "Knowledge and Skills Assessment Agency (UzBMB)",
            "description_uz": "Oliy ta'lim muassasalariga qabul test sinovlari haqida ma'lumot",
            "description_ru": "Информация о вступительных тестах в вузы Узбекистана",
            "description_en": "Information on entrance tests to higher education institutions in Uzbekistan",
            "url": "https://uzbmb.uz",
            "icon_class": "fas fa-clipboard-check",
        },
        {
            "title_uz": "Lex.uz — Qonunchilik ma'lumotlari milliy bazasi",
            "title_ru": "Lex.uz — Национальная база данных законодательства",
            "title_en": "Lex.uz — National Database of Legislation",
            "description_uz": "Ta'limga oid barcha qonun hujjatlari va qarorlar",
            "description_ru": "Все законодательные акты и постановления в сфере образования",
            "description_en": "All legislative acts and decrees related to education in Uzbekistan",
            "url": "https://lex.uz",
            "icon_class": "fas fa-gavel",
        },
        {
            "title_uz": "ZiyoNET ta'lim tarmog'i",
            "title_ru": "Образовательная сеть ZiyoNET",
            "title_en": "ZiyoNET Educational Network",
            "description_uz": "Yoshlar va talabalar uchun yagona axborot-ta'lim tarmog'i",
            "description_ru": "Единая информационно-образовательная сеть для молодёжи и студентов",
            "description_en": "Unified informational and educational network for youth and students",
            "url": "https://ziyonet.uz",
            "icon_class": "fas fa-book-open",
        },
        {
            "title_uz": "Yagona interaktiv davlat xizmatlari portali (my.gov.uz)",
            "title_ru": "Единый портал интерактивных государственных услуг (my.gov.uz)",
            "title_en": "Single Portal of Interactive State Services (my.gov.uz)",
            "description_uz": "Abituriyentlar uchun hujjat topshirish va boshqa davlat xizmatlari",
            "description_ru": "Подача документов для абитуриентов и иные государственные услуги",
            "description_en": "Document submission for applicants and other e-government services",
            "url": "https://my.gov.uz",
            "icon_class": "fas fa-laptop-house",
        },
        {
            "title_uz": "O'zbekiston Respublikasi Prezidenti portali — ta'lim yangiliklari",
            "title_ru": "Портал Президента Республики Узбекистан — новости образования",
            "title_en": "Presidential Portal of Uzbekistan — Education News",
            "description_uz": "Prezident qarorlari va farmonlari, ta'lim sohasidagi islohotlar",
            "description_ru": "Указы и постановления Президента, реформы в сфере образования",
            "description_en": "Presidential decrees and resolutions, education sector reforms",
            "url": "https://president.uz",
            "icon_class": "fas fa-landmark",
        },
        {
            "title_uz": "HEMIS — Oliy ta'limni boshqarish axborot tizimi",
            "title_ru": "HEMIS — Информационная система управления высшим образованием",
            "title_en": "HEMIS — Higher Education Management Information System",
            "description_uz": "Oliy ta'limdagi elektron reyestr, talabalar va o'qituvchilar ma'lumotlar bazasi",
            "description_ru": "Электронный реестр высшего образования, база данных студентов и преподавателей",
            "description_en": "Electronic registry of higher education, student and faculty database",
            "url": "https://hemis.uz",
            "icon_class": "fas fa-database",
        },
        {
            "title_uz": "OTM Reytingi — O'zbekiston universitetlari milliy reytingi",
            "title_ru": "Рейтинг вузов Узбекистана (OTM Reytingi)",
            "title_en": "Uzbekistan University National Rankings (OTM Reytingi)",
            "description_uz": "Oliy ta'lim muassasalarining milliy reytingi va ko'rsatkichlari",
            "description_ru": "Национальный рейтинг высших учебных заведений и их показатели",
            "description_en": "National rating of higher educational institutions and their performance indicators",
            "url": "https://reyting.edu.uz",
            "icon_class": "fas fa-star",
        },
        {
            "title_uz": "El-yurt umidi jamg'armasi — xorij grantlari",
            "title_ru": "Фонд «Эл-юрт умиди» — зарубежные гранты",
            "title_en": "El-Yurt Umidi Foundation — Overseas Scholarships",
            "description_uz": "Xorijda o'qish uchun davlat grantlari va stipendiyalar",
            "description_ru": "Государственные гранты и стипендии для обучения за рубежом",
            "description_en": "State grants and scholarships for studying abroad",
            "url": "https://eyu.uz",
            "icon_class": "fas fa-globe",
        },
        {
            "title_uz": "Yoshlar ishlar agentligi — grantlar va dasturlar",
            "title_ru": "Агентство по делам молодёжи — гранты и программы",
            "title_en": "Youth Affairs Agency of Uzbekistan — Grants and Programmes",
            "description_uz": "Talabalar uchun grantlar, stipendiyalar va yoshlar dasturlari",
            "description_ru": "Гранты, стипендии и молодёжные программы для студентов",
            "description_en": "Grants, scholarships and youth programmes for students of Uzbekistan",
            "url": "https://yia.uz",
            "icon_class": "fas fa-users",
        },
        {
            "title_uz": "O'zbekiston ilmiy-texnik axborot markazi (O'zSAM)",
            "title_ru": "Узбекский центр научно-технической информации (УзСАМ)",
            "title_en": "Uzbek Center for Scientific and Technical Information (UzSAM)",
            "description_uz": "Ilmiy maqolalar, dissertatsiyalar va tadqiqotlarga kirish imkoniyati",
            "description_ru": "Доступ к научным статьям, диссертациям и исследованиям",
            "description_en": "Access to scientific articles, dissertations and research papers of Uzbekistan",
            "url": "https://uzsam.uz",
            "icon_class": "fas fa-microscope",
        },
        {
            "title_uz": "Talabalar ilmiy jamiyati portali",
            "title_ru": "Портал студенческих научных обществ",
            "title_en": "Student Scientific Society Portal",
            "description_uz": "O'zbekiston universitetlari talabalari ilmiy faoliyati haqida ma'lumotlar",
            "description_ru": "Сведения о научной деятельности студентов университетов Узбекистана",
            "description_en": "Information on scientific activities of university students in Uzbekistan",
            "url": "https://student.edu.uz",
            "icon_class": "fas fa-flask",
        },
        {
            "title_uz": "Xalqaro diplom tan olish portali",
            "title_ru": "Портал международного признания дипломов",
            "title_en": "International Diploma Recognition Portal",
            "description_uz": "Chet el va O'zbekiston diplom va sertifikatlarini tan olish tartibi",
            "description_ru": "Порядок признания иностранных и узбекистанских дипломов и сертификатов",
            "description_en": "Procedure for recognition of foreign and Uzbek diplomas and certificates",
            "url": "https://recognition.edu.uz",
            "icon_class": "fas fa-certificate",
        },
        {
            "title_uz": "UNESCO O'zbekiston ta'lim statistikasi",
            "title_ru": "Статистика образования в Узбекистане — ЮНЕСКО",
            "title_en": "UNESCO Education Statistics for Uzbekistan",
            "description_uz": "Xalqaro tashkilotning O'zbekistondagi ta'lim statistikasi va hisobotlari",
            "description_ru": "Статистика и отчёты международной организации по образованию в Узбекистане",
            "description_en": "International organization statistics and reports on education in Uzbekistan",
            "url": "https://uis.unesco.org/en/country/uz",
            "icon_class": "fas fa-chart-pie",
        },
        {
            "title_uz": "QS World University Rankings — O'zbekiston universitetlari",
            "title_ru": "QS World University Rankings — университеты Узбекистана",
            "title_en": "QS World University Rankings — Uzbekistan Universities",
            "description_uz": "Dunyo universitetlari reytingida O'zbekiston oliy ta'lim muassasalari",
            "description_ru": "Высшие учебные заведения Узбекистана в мировом рейтинге QS",
            "description_en": "Uzbekistan universities in the global QS World University Rankings",
            "url": "https://www.topuniversities.com/where-to-study/asia/uzbekistan",
            "icon_class": "fas fa-trophy",
        },
        {
            "title_uz": "Xalqaro talabalar almashinuvi — Erasmus+ O'zbekistonda",
            "title_ru": "Международный обмен студентами — Erasmus+ в Узбекистане",
            "title_en": "International Student Exchange — Erasmus+ in Uzbekistan",
            "description_uz": "Yevropa universitetlari bilan talabalar almashinuvi dasturlari",
            "description_ru": "Программы обмена студентами с европейскими университетами",
            "description_en": "Student exchange programmes with European universities via Erasmus+",
            "url": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students",
            "icon_class": "fas fa-exchange-alt",
        },
    ]

    for res in resources_data:
        obj, created = AdditionalResource.objects.update_or_create(
            url=res["url"],
            defaults=res,
        )
        action = "yangi qo'shildi" if created else "yangilandi"
        print(f"  Manba: {obj.title_uz} ({action})")

    total = AdditionalResource.objects.count()
    print(f"\n  Jami manbalar soni: {total}")


def seed_data():
    print("\n═══ REGIONS ═══")
    region_map = seed_regions()

    print("\n═══ UNIVERSITIES ═══")
    seed_universities(region_map)

    print("\n═══ RESOURCES ═══")
    seed_resources()

    print("\n✅ Seed muvaffaqiyatli yakunlandi!")


if __name__ == '__main__':
    seed_data()