# Generated by Django 5.2.8 on 2025-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdegree',
            options={'verbose_name': 'Akademik daraja', 'verbose_name_plural': 'Akademik daraja'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='directionsubject',
            options={'verbose_name': "Yo'nalish va fan", 'verbose_name_plural': "Yo'nalishlar va fanlar"},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='employeesubject',
            options={'verbose_name': 'Hodim va fan', 'verbose_name_plural': 'Hodimlar va fanlar'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='kafedra',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='positiondegree',
            options={'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='employee',
        ),
        migrations.AddField(
            model_name='university',
            name='employee',
            field=models.ManyToManyField(blank=True, to='university.employee'),
        ),
    ]
