# Generated by Django 5.2.8 on 2026-02-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_academicdegree_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kafedras', to='university.faculty'),
        ),
    ]
