# Generated by Django 5.2.8 on 2026-04-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_testquestion_profile_testoption_usertestresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directionsubject',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='employeesubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employee',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='directionsubject',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='directionsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeesubject',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='university',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='employee',
        ),

        migrations.RemoveField(
            model_name='employeesubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='kafedra',
        ),
        migrations.DeleteModel(
            name='AcademicDegree',
        ),
        migrations.DeleteModel(
            name='DirectionSubject',
        ),
        migrations.DeleteModel(
            name='PositionDegree',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeSubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Kafedra',
        ),
    ]
