# Generated by Django 5.2.8 on 2026-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_employee_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(default='fas fa-link', help_text='FontAwesome icon class (e.g. fas fa-globe)', max_length=100)),
            ],
            options={
                'verbose_name': "Qo'shimcha manba",
                'verbose_name_plural': "Qo'shimcha manbalar",
            },
        ),
    ]
