# Generated by Django 5.2.8 on 2026-05-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_additionalresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='additionalresource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testoption',
            name='text',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='university',
            name='name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (Русский)'),
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Tavsif (O'zbekcha)"),
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='title_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (Русский)'),
        ),
        migrations.AddField(
            model_name='additionalresource',
            name='title_uz',
            field=models.CharField(default='', max_length=255, verbose_name="Sarlavha (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Direction Name (English)'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название направления (Русский)'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name="Yo'nalish nomi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Province Name (English)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название провинции (Русский)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name="Viloyat nomi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testoption',
            name='text_en',
            field=models.CharField(default='', max_length=255, verbose_name='Test Option (English)'),
        ),
        migrations.AddField(
            model_name='testoption',
            name='text_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Вариант теста (Русский)'),
        ),
        migrations.AddField(
            model_name='testoption',
            name='text_uz',
            field=models.CharField(default='', max_length=255, verbose_name="Test varianti (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='text_en',
            field=models.TextField(default='', verbose_name='Test Question (English)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='text_ru',
            field=models.TextField(default='', verbose_name='Вопрос теста (Русский)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='text_uz',
            field=models.TextField(default='', verbose_name="Test savoli (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='University Name (English)'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название университета (Русский)'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name="Universitet nomi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='postal_address_en',
            field=models.TextField(default='', verbose_name='Postal Address (English)'),
        ),
        migrations.AddField(
            model_name='university',
            name='postal_address_ru',
            field=models.TextField(default='', verbose_name='Почтовый адрес (Русский)'),
        ),
        migrations.AddField(
            model_name='university',
            name='postal_address_uz',
            field=models.TextField(default='', verbose_name="Pochtali manzil (O'zbekcha)"),
            preserve_default=False,
        ),
    ]
