# Generated by Django 5.2.8 on 2026-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_additionalresource_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalresource',
            options={'ordering': ['title_uz'], 'verbose_name': "Qo'shimcha manba", 'verbose_name_plural': "Qo'shimcha manbalar"},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name_uz'], 'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name_uz'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='testoption',
            options={'ordering': ['question', 'id'], 'verbose_name': 'Test varianti', 'verbose_name_plural': 'Test variantlari'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['-created_date'], 'verbose_name': 'Test savoli', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name_uz'], 'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'ordering': ['-created_date'], 'verbose_name': 'Test natijasi', 'verbose_name_plural': 'Test natijalari'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
