# Generated by Django 5.2.8 on 2026-05-21 13:55

from django.db import migrations


def create_google_social_app(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    from django.conf import settings

    site_domain = getattr(settings, 'SITE_DOMAIN', 'localhost:8000')
    site_name = getattr(settings, 'SITE_NAME', 'Universitys Local')

    site, _ = Site.objects.get_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': site_domain, 'name': site_name},
    )
    if site.domain != site_domain or site.name != site_name:
        site.domain = site_domain
        site.name = site_name
        site.save()

    if settings.GOOGLE_CLIENT_ID and settings.GOOGLE_CLIENT_SECRET:
        app, _ = SocialApp.objects.get_or_create(
            provider='google',
            defaults={
                'name': 'Google',
                'client_id': settings.GOOGLE_CLIENT_ID,
                'secret': settings.GOOGLE_CLIENT_SECRET,
                'key': '',
            },
        )
        if site not in app.sites.all():
            app.sites.add(site)
            app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_additionalresource_options_and_more'),
        ('sites', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_google_social_app, reverse_code=migrations.RunPython.noop),
    ]
